server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #表示是否与服务发现组件（register）进行结合，通过 serviceId（必须设置成大写）转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。路由访问方式：http://Gateway_HOST:Gateway_PORT/ 大写的 serviceId/**，其中微服务应用名默认大写访问。 logging.level：日志配置策略。
logging:
  level:
     org.springframework.cloud.gateway: trace
     org.springframework.http.server.reactive: debug
     org.springframework.web.reactive: debug
     reactor.ipc.netty: debug    #日志配置策略。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心默认地址。